parameters:
  flutterVersion: 'stable'
  fvmVersion: ''
  sonarConnectionName: ''
  sonarProjectName: ''
  sonarProjetKey: ''
  sources: 'lib,pubspec.yaml'
  tests: 'test'
  reportPath: $(Build.SourcesDirectory)/analyze.txt
  reportFileName: 'analyze.txt'

jobs:
  - job: Sonar_analysis
    displayName: Sonar analysis

    steps:
      - template: ../tasks/task_init.yml
        parameters:
          flutterVersion: ${{ parameters.flutterVersion }}
          fvmVersion: ${{ parameters.fvmVersion }}

      - template: ../tasks/task_prepare_sonar.yml
        parameters:
          sonarConnectionName: ${{ parameters.sonarConnectionName }}
          sonarProjectName: ${{ parameters.sonarProjectName }}
          sonarProjetKey: ${{ parameters.sonarProjetKey }}
          sources: ${{ parameters.sources }}
          tests: ${{ parameters.tests }}
          reportPath: ${{ parameters.reportPath }}

      - template: ../tasks/task_flutter_tests_coverage.yml

      - template: ../tasks/task_flutter_analyze.yml
        parameters:
          reportFileName: ${{ parameters.reportFileName }}

      - task: SonarQubeAnalyze@5
        displayName: Run analyze

      - task: SonarQubePublish@5
        displayName: Run publish
        inputs:
          pollingTimeoutSec: '300'
